/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string;

export interface Unit {
  /**
   * A relative URL to either a .obj or .unity3d file.
   */
  render: string;
  texture:
    | Image
    | {
        red: Image;
        blue: Image;
        [k: string]: any;
      };
}
