name: Lua CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v5
      - uses: leafo/gh-actions-luarocks@v2

      - name: build
        run: |
          luarocks install ldoc
          luarocks make https://luarocks.org/manifests/luarocks/ldoc-1.4.2-1.rockspec

      - name: ldoc
        run: |
          ldoc -d ldoc mod

  deploy:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2
