name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    # TODO: Run on all platforms.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build --skip-linking

      - name: Save
        uses: actions/upload-artifact@v1
        with:
          name: build-files
          path: .build
